trigger:
  - master

pool:
  name: Hosted Ubuntu 1604

steps:
  - task: DotNetCoreInstaller@0
    displayName: "Use .NET Core 3 SDK"
    inputs:
      version: "3.0.100-preview3-010431"

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: "$(Projects)"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: "$(Projects)"
      arguments: "--configuration $(BuildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: "$(TestProjects)"
      arguments: '--configuration $(BuildConfiguration) --collect "Code coverage"'

  - task: Docker@1
    displayName: "Build an image"
    inputs:
      command: Build an image
      containerregistrytype: "Container Registry"
      dockerRegistryEndpoint: "Docker Hub"
      dockerFile: RazzleServer/Dockerfile
      includeLatestTag: true

  - task: Docker@1
    displayName: "Push an image"
    inputs:
      containerregistrytype: "Container Registry"
      dockerRegistryEndpoint: "Docker Hub"
      command: "Push an image"
