version: '3.7'

services:
  razzleserver:
    image: razzleserver
    volumes:
    - ./RazzleServer/ServerConfig.json:/app/ServerConfig.json:ro
    build:
      context: .
      dockerfile: RazzleServer/Dockerfile
